# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_auto_20190316_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
