# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_auto_20190316_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=2)),
                ('company_name', models.CharField(max_length=35)),
                ('due_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
