# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_addplacement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddPlacement',
        ),
    ]
