# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0008_auto_20190404_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(max_length=10, unique=''),
        ),
    ]
