# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addplacement',
            name='company_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='addplacement',
            name='criteria',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='addplacement',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Due Date'),
        ),
    ]
