# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterdStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='', max_length=10)),
                ('student_cpi', models.FloatField(default=0.0, max_length=6)),
                ('firstname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('department', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='registerdstudents',
            name='registered_student_ucpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rcpi', to='student.StudentDetails'),
        ),
        migrations.AddField(
            model_name='registerdstudents',
            name='registered_student_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rid', to='student.StudentDetails'),
        ),
    ]
