# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdstudents',
            old_name='registered_student_uid',
            new_name='registered_student_name',
        ),
        migrations.RemoveField(
            model_name='registerdstudents',
            name='registered_student_ucpi',
        ),
    ]
