# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190405_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdstudents',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='a', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='registerdstudents',
            name='registered_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_rid', to='student.StudentDetails'),
        ),
    ]
