# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190405_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='slug',
        ),
        migrations.AddField(
            model_name='registerdstudents',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='a', verbose_name='Slug'),
        ),
    ]
