# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20190406_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug'),
        ),
    ]
