# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190404_2057'),
        ('student', '0011_auto_20190406_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdstudents',
            name='place_comapany_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addplace', to='teacher.AddPlacement'),
        ),
    ]
