# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20190406_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdstudents',
            name='place_comapany_name',
        ),
        migrations.AddField(
            model_name='registerdstudents',
            name='place_comapany_id',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
