# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_registerdstudents_place_comapany_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdstudents',
            name='comp_id',
            field=models.IntegerField(default=0),
        ),
    ]
