# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_registerdstudents_comp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdstudents',
            name='comp_id',
            field=models.SlugField(default=0, unique=True, verbose_name='Company Name'),
        ),
    ]
