# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20190406_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdstudents',
            old_name='comp_id',
            new_name='slug',
        ),
    ]
